services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata: {}
